"""Subclass of settings_dialog, which is generated by wxFormBuilder."""
import os
import re

import wx

from . import dialog_base

def pop_error(msg):
    wx.MessageBox(msg, 'Error', wx.OK | wx.ICON_ERROR)


class SettingsDialog(dialog_base.SettingsDialogBase):
    def __init__(self, config_save_func,
                 file_name_format_hint, version):
        dialog_base.SettingsDialogBase.__init__(self, None)
        self.panel = SettingsDialogPanel(
                self, config_save_func, file_name_format_hint)
        best_size = self.panel.BestSize
        # hack for some gtk themes that incorrectly calculate best size
        best_size.IncBy(dx=0, dy=30)
        self.SetClientSize(best_size)
        self.SetTitle('KiZip %s' % version)

    # hack for new wxFormBuilder generating code incompatible with old wxPython
    # noinspection PyMethodOverriding
    def SetSizeHints(self, sz1, sz2):
        try:
            # wxPython 3
            self.SetSizeHintsSz(sz1, sz2)
        except TypeError:
            # wxPython 4
            super(SettingsDialog, self).SetSizeHints(sz1, sz2)



# Implementing settings_dialog
class SettingsDialogPanel(dialog_base.SettingsDialogPanel):
    def __init__(self, parent, config_save_func,
                 file_name_format_hint):
        self.config_save_func = config_save_func
        dialog_base.SettingsDialogPanel.__init__(self, parent)
        self.general = GeneralSettingsPanel(self.notebook,file_name_format_hint)
        self.notebook.AddPage(self.general, "General")

        self.layers = LayerSettingsPanel(self.notebook)
        self.notebook.AddPage(self.layers, "Layers")
        
    def OnExit(self, event):
        self.GetParent().EndModal(wx.ID_CANCEL)

    def OnSaveSettings(self, event):
        self.config_save_func(self)

    def OnGenerateGerbers(self, event):
        self.GetParent().EndModal(wx.ID_OK)

    def finish_init(self):
        self.html.OnBoardRotationSlider(None)

# Implementing GeneralSettingsPanelBase
class GeneralSettingsPanel(dialog_base.GeneralSettingsPanelBase):

    def __init__(self, parent, file_name_format_hint):
        dialog_base.GeneralSettingsPanelBase.__init__(self, parent)
        self.file_name_format_hint = file_name_format_hint

    def OnNameFormatHintClick(self, event):
        wx.MessageBox(self.file_name_format_hint, 'File name format help',
                      style=wx.ICON_NONE | wx.OK)


# Implementing LayerSettingsPanelBase
class LayerSettingsPanel(dialog_base.LayerSettingsPanelBase):

    def __init__(self, parent):
        dialog_base.LayerSettingsPanelBase.__init__(self, parent)

        self.selected = []

        # Add column
        self.LayerList.InsertColumn(0, 'Layer (KiCad_ID)', width=150)
        self.LayerList.InsertColumn(1, 'ext', width=150)

        self.m_button17.Disable()

        self.UpdateListSelections()

    def OnEditLayer(self, event):
        dlg = AddLayerDialog(None)
        result = dlg.ShowModal()
        print(result)

    def Select(self, item):
        if item in self.selected:
            self.selected.remove(item)
        else:
            self.selected.append(item)

        

    def UpdateListSelections(self):
        for d in range(self.LayerList.GetItemCount()):
            self.LayerList.SetItemBackgroundColour(d, (-1, -1, -1, 255))
            self.LayerList.SetItemState(d, 0, wx.LIST_STATE_SELECTED | wx.LIST_STATE_FOCUSED | wx.LIST_STATE_PICKED)
            if d in self.selected:
                self.LayerList.SetItemBackgroundColour(d, 'Orange')
            else:
                ...
        if self.LayerList.GetItemCount() > 0:
            self.LayerList.RefreshItems(0, self.LayerList.GetItemCount()-1)

    def OnLeftDown(self,event):
        item, flags = self.LayerList.HitTest(event.GetPosition())
        if flags & wx.LIST_HITTEST_ONITEM:
            if item > -1:
                self.Select(item)
            else:
                event.Skip()
        self.UpdateListSelections()
    

    def OnMouse(self,event):
        self.UpdateListSelections()
        event.Skip()

# Implementing LayerSettingsPanelBase
class AddLayerDialog(dialog_base.AddLayerDialog):
    def __init__(self, parent):
        dialog_base.AddLayerDialog.__init__(self, parent)


        