"""Subclass of settings_dialog, which is generated by wxFormBuilder."""
import os
import re

import wx

from . import dialog_base

def pop_error(msg):
    wx.MessageBox(msg, 'Error', wx.OK | wx.ICON_ERROR)


class SettingsDialog(dialog_base.SettingsDialogBase):
    def __init__(self, config_save_func,
                 file_name_format_hint, version):
        dialog_base.SettingsDialogBase.__init__(self, None)
        self.panel = SettingsDialogPanel(
                self, config_save_func, file_name_format_hint)
        best_size = self.panel.BestSize
        # hack for some gtk themes that incorrectly calculate best size
        best_size.IncBy(dx=0, dy=30)
        self.SetClientSize(best_size)
        self.SetTitle('KiZip %s' % version)

    # hack for new wxFormBuilder generating code incompatible with old wxPython
    # noinspection PyMethodOverriding
    def SetSizeHints(self, sz1, sz2):
        try:
            # wxPython 3
            self.SetSizeHintsSz(sz1, sz2)
        except TypeError:
            # wxPython 4
            super(SettingsDialog, self).SetSizeHints(sz1, sz2)



# Implementing settings_dialog
class SettingsDialogPanel(dialog_base.SettingsDialogPanel):
    def __init__(self, parent, config_save_func,
                 file_name_format_hint):
        self.config_save_func = config_save_func
        dialog_base.SettingsDialogPanel.__init__(self, parent)
        self.general = GeneralSettingsPanel(self.notebook,file_name_format_hint)
        self.notebook.AddPage(self.general, "General")

        self.layers = LayerSettingsPanel(self.notebook)
        self.notebook.AddPage(self.layers, "Layers")
        
    def OnExit(self, event):
        self.GetParent().EndModal(wx.ID_CANCEL)

    def OnSaveSettings(self, event):
        self.config_save_func(self)

    def OnGenerateGerbers(self, event):
        self.GetParent().EndModal(wx.ID_OK)

    def finish_init(self):
        self.html.OnBoardRotationSlider(None)

# Implementing GeneralSettingsPanelBase
class GeneralSettingsPanel(dialog_base.GeneralSettingsPanelBase):

    def __init__(self, parent, file_name_format_hint):
        dialog_base.GeneralSettingsPanelBase.__init__(self, parent)
        self.file_name_format_hint = file_name_format_hint

    def OnNameFormatHintClick(self, event):
        wx.MessageBox(self.file_name_format_hint, 'File name format help',
                      style=wx.ICON_NONE | wx.OK)


# Implementing LayerSettingsPanelBase
class LayerSettingsPanel(dialog_base.LayerSettingsPanelBase):

    def __init__(self, parent):
        dialog_base.LayerSettingsPanelBase.__init__(self, parent)

        self.layers = []
        self.bSizer = wx.BoxSizer( wx.VERTICAL )
        self.LayerPanelArea.SetSizer(self.bSizer)

        
    def AddLayer(self, enabled, name, ext):
        # Create wx element and add to scroll box
        pnl = LayerItemPanelBase(self.LayerPanelArea, enabled, name, ext)
        self.bSizer.Add(pnl, 0, wx.EXPAND, 5 )
        self.layers += [pnl]


# Implementing LayerSettingsPanelBase
class LayerItemPanelBase(dialog_base.LayerItemPanelBase):
    def __init__(self, parent, enabled, name, ext):
        dialog_base.LayerItemPanelBase.__init__(self, parent)

        self.LayerEnabledCheckbox.SetLabel(name)
        self.LayerEnabledCheckbox.SetValue(enabled)
        self.Extension.SetValue(ext)

        self.name = name
    
    def IsEnabled(self):
        return self.LayerEnabledCheckbox.IsChecked()

    def GetExtension(self):
        return self.Extension.GetValue()


        